Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  DefaultContextTimeout: 5
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
ApiClient: # api配置
  AccessTokenIdentity: x-api-key
  AccessTokenValidity: true
  AccessTokenExpire: 63072000
  RefreshTokenValidity: true
  RefreshTokenExpire: 2592000
  # 验签
  HttpSignValidity: false
  HttpSignExpire: 60
  HttpSignAccount:
    Key: f29388d280554040
    Secret: 756fcebffbe983d7
Wechat: # 微信配置
  Work: # 企微
    WebHook:
      EndPoint: https://qyapi.weixin.qq.com/cgi-bin/webhook/send
      Key: c0943728-906d-4151-b95f-9391caebfe2a